services:
  mysql:
    container_name: mysql-kanban_api
    image: mysql:8.0-oracle
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - kanban-net

  pma:
    container_name: pma-kanban_api
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_HOST: mysql-kanban_api
    ports:
      - '9000:80'
    depends_on:
      - mysql
    networks:
      - kanban-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kanban-api:latest
    container_name: kanban-api
    restart: on-failure
    depends_on:
      - mysql
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - kanban-net

networks:
  kanban-net:
    driver: bridge
