version: "3.9"
services:
  mysql:
    container_name: mysql-kanban_api
    image: mysql:8.0-oracle
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root

  pma:
    container_name: pma-kanban_api
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_HOST: mysql-kanban_api
    ports:
      - '9000:80'
    depends_on:
      - mysql